root_redirect: # Redirection de la racine vers une langue par défaut
    path: / # Route de la racine
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: app_home # Nom de la route
        permanent: true # Statut HTTP (301)
        _locale: en # Langue par défaut

controllers:
    prefix: /{_locale}/ # Préfixe de la racine de l'application
    requirements: 
        _locale: en|fr|es # Langues supportées
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute